version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80" # Expose port 80 for HTTP
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Mount the Nginx configuration file
    depends_on:
      - webapp

  webapp:
    image: your-node-app:latest
    container_name: webapp
    ports:
      - "8080:8080" # Internal port for the web app
    environment:
      - NODE_ENV=production

  mongo:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017" # Expose MongoDB
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: